- gulpfile.js
- package.json
- src/main/js/app.js
> Add possibility to use ES2015

- gulpfile.js
- package.json
- src/main/js/actions/ActionCreator.js
- src/main/js/components/Table.jsx
- src/main/js/components/TableView.jsx
- src/main/js/components/Tableaux.jsx
- src/main/js/components/ViewRenderer.jsx
- src/main/js/components/header/TableSwitcher.jsx
- src/main/js/components/media/MediaView.jsx
- src/main/js/components/media/folder/Folder.jsx
- src/main/js/components/media/folder/SubfolderView.jsx
- src/main/js/constants/TableauxConstants.js
- src/main/js/router.js
- src/main/scss/media.scss
@Pixlschmied Please review and test tables view
> refactor for a common base for media management and tables

- src/main/js/components/Tableaux.jsx
- src/main/js/components/header/TableSwitcher.jsx
- src/main/js/models/Table.js
- src/main/js/models/Tables.js
@Pixlschmied please review. Should work with stand-alone and especially with https://github.com/campudus/tableaux/pull/139
> Add display names for table and port touched parts to ES6

- src/main/js/components/media/folder/Folder.jsx
- src/main/js/components/overlay/PasteMultilanguageCellInfo.jsx
- src/main/js/helpers/RowConcatHelper.js
- src/main/js/models/media/File.js
- src/main/scss/media.scss
in media view:
- highlight files added since folder opened
- sort files by update time
- forget highlighting on folder change
> Highlight new files

- src/main/js/components/cells/link/LinkOverlay.jsx
- src/main/js/components/cells/link/LinkOverlayFragments.jsx
- src/main/scss/linkoverlay.scss
- Allow to switch between order of rowId and alphabetical sorting
- Maybe the icons need some touching up...
> Sort unlinked elements in LinkOverlay

- src/main/js/components/columns/ColumnEntry.jsx
- src/main/js/components/columns/ColumnHeader.jsx
- src/main/js/components/tableView/TableView.jsx
- src/main/scss/cells/cell.scss
- shorttext cell input width
- can't delete column descriptions
- jump-to-cell and sorting overlays stack when opening tables
- column menu icon is visible on concat columns while menu is empty
> Number of small patches

- src/main/js/components/cells/attachment/AttachmentOverlay.jsx
- src/main/js/components/cells/attachment/AttachmentOverlayFilter.jsx
- src/main/scss/attachmentOverlayFilter.scss
- src/main/scss/main.scss
- src/main/scss/media.scss
- filter (begins / starts_with)
- sort either by file name or creation date
> Allow filtering and sorting files in the AttachmentOverlay

- src/main/js/components/Tableaux.jsx
- src/main/js/components/media/MediaLink.jsx
- src/main/js/components/media/MediaView.jsx
- src/main/js/components/media/overlay/FileEdit.jsx
- src/main/js/components/media/overlay/MultiFileEdit.jsx
- src/main/js/components/media/overlay/MultifileFileEdit.jsx
- src/main/js/components/media/overlay/MultilangFileDropzone.jsx
- src/main/js/components/media/overlay/SingleFileEdit.jsx
- src/main/js/components/media/overlay/SingleFileTextInput.jsx
- fix: can't edit file metadata
- fix: can't open file preview
- fix: missing redraws
> Refactor media file overlay

- package.json
- src/main/js/components/textannotations/AnnotationPopup.jsx
- use focus-trap-react to catch focus from falling into table
- reset focus on input blur or on mouseclicks inside the popup
> Make sure focus stays inside comment popup in firefox

- src/main/js/models/Column.js
- src/main/js/models/helpers/getDisplayValue.js
- src/main/js/specs/SpecTest.js
changed frontend that it  works with columnIds in formatPattern instead of index position
> Format pattern | 

- src/main/js/models/Row.js
prevent links from being inserted when rows are duplicated
in columns with a FROM cardinality greater than zero
> changed row duplication behavior

- src/app/components/frontendService/FrontendServiceView.jsx
Prop name changed fell through review process :D
> Fix service names showing `undefined`

- package-lock.json
- src/app/components/cells/text/TextCell.jsx
- src/app/components/entityView/RowHeadline.jsx
- src/app/components/markdownEditor/MarkdownEditor.jsx
- src/locales/de/table.json
- src/locales/en/table.json
This is just about the integration of the markdown editor into the entity view (althoug bug reports about the markdown editor itself are welcome, of course)
> Feature/markdown editor/entity view integration

- src/app/components/table/tableNavigationWorker.js
Reconstruct missing cell type information. Cache it for performance.
> Start edit mode when typing in compatible cells

- .npmrc
- Dockerfile
- Jenkinsfile
- package-lock.json
- package.json
- src/app/components/cells/text/TextEditOverlay.jsx
added `lint` and `test` task to jenkins pipeline
> Test and lint

- src/app/components/columns/ColumnEntry.jsx
- src/app/components/columns/ColumnHeader.jsx
- src/app/components/header/ColumnFilterPopup.jsx
- src/app/components/table/VirtualTable.jsx
- src/scss/columnFilter.scss
- src/scss/table.scss
Only move the line while resizing and update table after resize,
preventing lag.
> Show line on idColumn resize

- src/app/components/cells/numeric/NumericCell.jsx
- src/app/redux/actions/annotationActions.js
> fix numeric multilang cells not working

- src/app/components/helperComponents/SvgIcon.jsx
- src/app/components/markdownEditor/EditorPanel.jsx
- src/app/components/markdownEditor/LinkEditor.jsx
- src/app/components/markdownEditor/MarkdownEditor.jsx
- src/app/components/markdownEditor/PlainMarkdownEditor.jsx
- src/app/components/markdownEditor/StyleControls.jsx
- src/locales/de/table.json
- src/locales/en/common.json
- src/locales/en/table.json
- src/scss/layout.scss
- src/scss/markdownEditor.scss
- src/static/img/icons/layout-horizontal.svg
- src/static/img/icons/layout-single.svg
- src/static/img/icons/layout-vertical.svg
- icons
- button layout
- link editor overlay
- fix some display/scrolling issues (how does it look on OSX?)
> Style markdown editors

- dev-server.js
- package-lock.json
- package.json
- src/static/ServerConfigTool.js
- src/static/grud-frontend-server.js
Mit einem Cherry-Pick von Manes #194
> Upgrade `/api` requests with auth token

- .gitignore
- package-lock.json
- package.json
dependency was missing
with version 8.0.0 also name of environment variable changed
> added missing dev dep for test:ci task

- src/app/components/header/ColumnFilterPopup.jsx
- src/locales/de/table.json
- src/locales/en/table.json
- src/scss/columnFilter.scss
- src/scss/layout.scss
Zeigt im "verborgene Spalten"-Menü eine Möglichkeit an, zu sichtbaren Spalten zu springen. Bekommt bestimmt später mal eine durchdachte UI und ein schönes Design. Zu ausgeblendeten Spalten können wir nicht springen, da das aufgrund mehrerer UI-Redraws nicht 100% zuverlässig funktioniert.
> Jump to column button

- src/app/components/cells/numeric/NumericEditCell.jsx
- src/app/components/cells/text/SelectableShortText.jsx
- src/app/components/helperComponents/NumberInput.jsx
Man sollte jetzt in Text- und Zahlenfeldern mit der Maus selektieren bzw. die Caretposition wählen können.
> Future auth/fix mouse selection

- Jenkinsfile
- the only change is, that the built docker image is pushed to a docker registry
- no tests touched
- no breaking changes
> changed Jenkinsfile to push image to registry

- src/app/components/cells/Cell.jsx
- src/app/components/cells/numeric/NumericCell.jsx
- src/app/components/cells/numeric/NumericEditCell.jsx
- src/app/components/helperComponents/NumberInput.jsx
- src/app/constants/TableauxConstants.js
- Tests
Add new separator flag for numeric values.
Add new Integer column.
> Numeric changes

- src/app/components/tableView/applyFiltersAndVisibility.js
- [ x] This is not a duplicate of another PR
- [ x] The correct target branch selected?
- [x ] No existing features have been broken (without good reason)
- [ x] Commit messages are meaningful
- [ x] The behaviour is as the documentation describes, or you updated the docs
- Tests
- [ x] The linter was run and did pass
Several Conditions responsible for showing the Cell Jump Overlay got lost, so they got readded and adapted to the Cell Navigation Updates.
> Fix Jump Overlay Conditions

- src/app/components/cells/Cell.jsx
- src/app/components/cells/MetaCell.jsx
- src/app/components/cells/link/LinkItem.jsx
- src/app/components/cells/numeric/NumericCell.jsx
- src/app/components/helperComponents/NumberInput.jsx
- src/app/components/table/VirtualTable.jsx
- src/app/components/table/tableNavigationWorker.js
- src/app/components/tableView/TableView.jsx
- src/app/helpers/accessManagementHelper.js
- src/app/redux/reducers/selectedCell.js
- src/app/redux/updateDependentTables.js
- src/scss/cells/cell.scss
- src/scss/datetimepicker.scss
- src/scss/header.scss
- src/scss/linkList.scss
- Tests
- center icon in cell edit button (was not centered in chrome)
- fix lock icon in MetaCell not changing
- fix selected row not being highlighted
- change cursor in LinkItem to default
- change curosr in DatePicker to pointer
- fix copy and paste by keyboard shortcuts
- fix positioning of paste button in grud header
- in LinkItem, check if link leads to a hidden table and if the user is allowed to see hidden tables
- reverse default for separator flag
> Various bug fixes

- src/app/components/cells/MetaCell.jsx
- Tests
Lock Icon didn't change immediately after change, add check to shouldComponentUpdate.
Task: https://app.activecollab.com/116706/projects/2?modal=Task-21768-2
> MetaCell now updates on final change

- src/app/components/cells/FlagIconRenderer.jsx
- Tests
Flag Icon renderer had a fatal error if annotations were null. Task: https://app.activecollab.com/116706/projects/2?modal=Task-21733-2
> Fix error if annotations are null

- src/app/redux/actions/annotationActions.js
- Tests
Could only toggle translation_required flag two times.
Task: https://app.activecollab.com/116706/projects/2?modal=Task-21761-2
> fix translation required not toggling

- src/app/components/overlay/EntityView/EntityViewBody.jsx
- src/app/components/table/VirtualTable.jsx
- src/app/redux/actionCreators.js
- Tests
When navigating through an expanded row the table lang changed, prevent this by not editing langtag in URL.
Task: https://app.activecollab.com/116706/projects/2?modal=Task-21719-2
> prevent language switch

- src/app/components/table/Table.jsx
- Tests
Removes event listener for window resize if table component is unmounted.
> remove event listener on table unmount

- src/index.js
- [ x The correct target branch selected?
- Tests
> refactore loading order of imports

- src/static/ServerConfigTool.js
> make catch compatible with older node versions

- src/app/components/cells/MetaCellHeader.jsx
- src/app/components/contextMenu/ColumnContextMenu.jsx
- src/app/components/table/RowFilters.js
- src/app/components/table/VirtualTable.jsx
- src/scss/table.scss
- Tests
Implements [Task #926:#926](https://app.activecollab.com/116706/projects/2/tasks/26066)
> Feature/sort by Id

- src/app/components/cells/text/SelectableShortText.jsx
- src/app/components/table/VirtualTable.jsx
- src/app/components/table/tableNavigationWorker.js
- Tests
Fixes [#931](https://app.activecollab.com/116706/projects/2/tasks/26269)
> fixed table focus errors

- package-lock.json
- package.json
- src/app/components/cells/Cell.jsx
- src/app/components/cells/link/LinkCell.jsx
- src/app/components/cells/link/getVisibleLinkCount.ts
- src/app/components/table/VirtualTable.jsx
- Added typescript, so we can gradually introduce typing. Parcel will automatically package ts files correctly.
> Issue 945 - More link previews in larger columns

- src/app/components/frontendService/FrontendServiceView.jsx
> 943: Add clipboard read/write permissions to iframes

- src/app/components/helperComponents/SessionUnlockDialog.jsx
> 724: Suppress unlock dialog when user can't edit

- src/app/components/entityView/RowView.jsx
- src/app/components/entityView/status/StatusView.jsx
- src/app/components/overlay/EntityView/HeaderPopupMenu.jsx
- src/app/components/table/RowFilters.js
*Add a short description what this PR does. E.g. "solves issue [link]" or "makes everything better"*
> run lint:fix

- src/app/helpers/apiRoutes.js
-------
When optional params is not set, destructuring it will fail.
> Provide default value for optional params

- src/app/components/frontendService/MainMenuEntry.jsx
- src/app/components/frontendService/ServiceLink.jsx
I did this changes directly on GitHub and could not test them locally :)
Fix missing prop in SerivceLink and added propTypes in ServiceLink
> Fix service link bug

- src/app/components/cells/text/SelectableShortText.jsx
*Add a short description what this PR does. E.g. "solves issue [link]" or "makes everything better"*
> Fix completion behaviour

- src/app/components/table/GrudGrid.jsx
- src/scss/table.scss
Apart from some linting and refactoring, the bugfix itself is undoing `4ce8ded6`. Status columns are not yet used "in the wild", so we have time to fix that problem in a better way.
> Fix scrolling bug

- src/app/components/cells/status/StatusCell.jsx
*Add a short description what this PR does. E.g. "solves issue [link]" or "makes everything better"*
> Organise imports

- src/app/components/cells/text/SelectableShortText.jsx
Fixes: https://app.activecollab.com/116706/projects/2/tasks/35803
> Fix Caret jumping to end while editing

- src/app/components/cells/text/SelectableShortText.jsx
- src/app/components/cells/text/ShortTextCell.jsx
Hier sind sich manchmal der getippte und der selektierte Wert in die Quere gekommen.
> Fix autocomplete not applying after typing

- src/app/components/markdownEditor/PlainMarkdownEditor.jsx
This fixes an embarrassing build problem (ran linter wrong before previous PR)
> Bugfix Linter

- src/app/redux/actionCreators.js
Somewhat of a Schrödingbug. Where did the row for the new EntityViews to show ever come from before that patch?
> Fix creating and adding of new rows

- src/app/components/overlay/SelectLinkTargetOverlay.jsx
- src/app/components/taxonomy/TaxonomyLinkOverlay.jsx
- src/app/components/taxonomy/TaxonomySelectLinkTargetOverlay.jsx
- src/app/components/taxonomy/taxonomy.js
- src/scss/TaxonomyLinkOverlay.scss
Fügt eine Baumansicht ins Neuverlinken gelöschter Zeilen ein.
> [Taxonomy] Select link target overlay

- src/app/components/cells/Cell.jsx
- src/app/components/cells/link/LinkItem.jsx
- src/app/components/entityView/RowHeadline.jsx
- src/app/components/entityView/link/LinkView.jsx
- src/app/components/helperComponents/LinkList.jsx
- src/app/components/media/folder/File.jsx
- src/app/helpers/accessManagementHelper.js
- src/scss/entityView/entityView.scss
AC-Task: https://app.activecollab.com/116706/projects/2?modal=Task-41151-2
> Frontend Permission Bugs -> AC-Task #980

- Jenkinsfile
Wenn ein image deplyoed ist, ist es schwer zu sehen wann es gebaut wurde und mit welchem Stand.
Mit `docker inspect` kann man die Infos wie labels am image damit einfach einsehen.
> added labels to docker image

- src/app/components/cells/attachment/AttachmentCell.jsx
- src/app/components/cells/attachment/AttachmentLabelCell.jsx
AC-Task: https://app.activecollab.com/116706/projects/2?modal=Task-44945-2
> Fix clickHandling behaviour in AttachmentCell and AttachmentLabelCell

- src/app/components/cells/text/ShortTextCell.jsx
> AC-1012: Fix empty shorttexts POSTing on render

- src/app/components/cells/link/LinkItem.jsx
- src/app/components/helperComponents/LinkList.jsx
> Feature: Open some attachments in new tabs

- src/app/components/header/filter/FilterPopup.jsx
- src/app/components/header/filter/FilterRow.jsx
- src/app/components/table/RowFilters.js
- src/app/constants/TableauxConstants.js
- src/app/helpers/searchFunctions.js
- src/locales/de/table.json
- src/locales/en/table.json
- tests/rowFilters/rowFilters.test.js
- tests/rowFilters/testData/shortTextColumnSortDesc.json
- tests/rowFilters/testData/sparseRows.json
- Refaktor der FilterRow-Komponente
- Refaktor der Zellwert-Filterfunktion
- Ersetzt ein paar Strings durch schon vorhandene Konstanten
- Fügt einen Filter für leere Werte hinzu
> Feature: Filter for empty items

- src/app/components/header/filter/FilterRow.jsx
> Fix "Any row contains..." filter input

- src/app/components/helperComponents/LinkList.jsx
- src/app/components/rows/DependentRowsList.jsx
- src/scss/overlay.scss
> AC-1023: Dependent links display error

- src/app/components/header/filter/FilterRow.jsx
> AC-1032: submit table filter on Enter

- src/app/components/header/ColumnFilterPopup.jsx
> [Bugfix] AC-1029: prevent navigation on click of show/hide all columns

- src/app/redux/reducers/tableView.js
> AC#1053/display all columns on columnReset or missing column configuration

- src/app/components/cells/cellCopyHelper.jsx
- src/app/components/table/GrudGrid.jsx
- src/app/components/table/VirtualTable.jsx
- src/app/helpers/array.js
- src/app/helpers/array.test.js
- src/app/helpers/promise.js
- src/app/helpers/promise.test.js
- src/app/redux/actions/cellActions.js
- src/app/redux/reducers/multiSelect.js
Hier ist etwas mehr Code als benötigt, weil ich etwas Zeit investiert hatte,
verschiedene Arten zu testen, die parallelen Requests in Batches zu unterteilen
und die Möglichkeiten noch verfügbar lassen wollte.
Am Ende ist das allerdings alles etwas moot, weil die Paste alle
one-off-Operationen sind... Diskussion dazu im Slack
> [Feature]: MCCP - Naive multiple pasting

- package.json
> AC#1054/fix build id in docker build

- src/app/components/cells/Cell.jsx
- src/app/components/cells/boolean/BooleanCell.jsx
- src/app/components/cells/currency/CurrencyCell.jsx
- src/app/components/cells/currency/CurrencyEditCell.jsx
- src/app/components/cells/date/DateEditCell.jsx
- src/app/components/cells/link/LinkEditCell.jsx
- src/app/components/cells/link/LinkOverlay.jsx
- src/app/components/cells/text/ExpandButton.jsx
- src/app/components/cells/text/TextCell.jsx
- src/app/components/cells/text/TextEditOverlay.jsx
- src/app/components/contextMenu/RowContextMenu.jsx
- src/app/components/entityView/ItemPopupMenu.jsx
- src/app/components/table/VirtualTable.jsx
- src/app/components/table/tableNavigationWorker.jsx
- src/app/constants/TableauxConstants.js
- src/app/helpers/KeyboardShortcutsHelper.js
- src/app/helpers/accessManagementHelper.js
- src/app/redux/actions/cellActions.js
- src/app/redux/actions/cellActions.test.js
- src/app/redux/reducers/selectedCell.js
- src/app/redux/redux-helpers.js
- src/locales/de/table.json
- src/locales/en/table.json
1. "Zellinhalte löschen"-Aktion löscht die ausgewählte Sprache der ausgewählten Zelle
2. Falls die Zelle mehrsprachig ist und die Primärsprache gelöscht wurde greift
der "Wollen Sie alle Zellinhalte löschen"-Dialog
- Tabelle: Rechtsklick-Kontextmenü->Zellinhalte löschen
- EntityView: Kontextmenü->Zellinhalte löschen
- `[Backspace]`
- `[Entfernen]`
> [Feature]: Add shortcuts to clear selected cells

- README.md
Ich hatte da etwas Probleme beim `npm i`. Letztendlich hat es geklappt, indem ich eine niedrigere python version verwendet habe. Das hab ich im readme festgehalten.
> docs: add troubleshooting section for npm install

- src/app/components/cells/link/LinkItem.jsx
> AC#1062/fix: add jpeg as viewable attachment

- src/app/redux/actionCreators.jsx
> AC#1064/Fix filter reset

- src/scss/entityView/entityView.scss
...plus Codeformat über das Style-File
> EntityView: Make link/attachment lists scrollable

- src/app/helpers/getDisplayValue.js
Ich hab jetzt Platzhalter mal dringelassen zum ausprobieren.  
Wenn das jetzt doch nicht gefällt einfach eine Suggestion drübercommiten, in der
der Placeholder zu `""` geändert wird, um das alte Verhalten "alles was leer ist
einfach leer anzeigen" zu übernehmen.
> Replace remaining moustaches in formatted strings

- src/app/components/cells/currency/CurrencyRow.jsx
> Bugfix: Currency Decimals

- src/app/components/Router.jsx
Mit der Änderung wird die TableView beim Ändern der Sprache nicht neu geladen.
Dadurch bleibt auch der aktuell gesetzte Filter erhalten.
> Fix filter reset on language change

- src/app/components/header/Navigation.jsx
> AC1071: Ensure navigation popup always closes on click

- Jenkinsfile
- src/app/components/taxonomy/taxonomy.test.js
~Schaltet den Performancetest ab, da manchmnal zirkuläre Bäume erstellt werden und wir keinen Einfluss auf den Random-Seed nehmen können.~
Nutzt einen einfachen Zufallsgenerator, so dass wir einen funktionierenden Baum reproduzieren können. Falls es weiter hängen sollte, einfach einen anderen Seed wählen.
> Skip flaky test

- src/app/components/entityView/RowView.jsx
- src/app/components/header/ColumnFilter.jsx
- src/app/components/header/ColumnFilterPopup.jsx
- src/app/components/table/VirtualTable.jsx
- src/app/components/tableView/applyFiltersAndVisibility.jsx
- src/app/helpers/columnHelper.js
- src/app/helpers/useLocalStorage.jsx
*Add a short description what this PR does. E.g. "solves issue [link]" or "makes everything better"*
> AC1074: Hide group member columns

- src/app/components/cells/currency/CurrencyCell.jsx
- src/app/components/cells/numeric/NumericCell.jsx
- src/app/components/cells/numeric/NumericEditCell.jsx
- src/app/components/entityView/numeric/NumericView.jsx
- src/app/components/helperComponents/NumberInput.jsx
- src/app/helpers/columnHelper.js
- src/app/helpers/functools.js
- src/app/helpers/multiLanguage.jsx
- src/app/helpers/multiLanguage.test.js
> Allow setting decimal digits

- src/app/components/cells/currency/CurrencyCell.jsx
- src/app/components/cells/currency/CurrencyEditCell.jsx
- src/app/components/cells/currency/CurrencyRow.jsx
- src/scss/cells/currency.scss
> AC#1098: Edit decimal digits in currency inputs

- package-lock.json
- src/app/components/header/tableSwitcher/TableSwitcherPopup.jsx
> AC#1042/prevent same table navigation

- src/app/components/table/VirtualTable.jsx
> AC#1055/update date format after lang change

- src/app/components/cells/Cell.jsx
- src/app/components/table/VirtualTable.jsx
> AC#1059/fix expanded row cell select with click

- src/app/components/cells/Cell.jsx
- src/app/components/table/tableNavigationWorker.jsx
> AC#1107/fix copy and paste for boolean cell

- src/app/components/header/ColumnFilterPopup.jsx
- src/app/components/table/RowFilters.js
> AC#1024/fix columns in ColumnFilterPopup

- src/app/components/header/tableSwitcher/TableSwitcherPopup.jsx
> AC#1112/fix navigation to search table

- src/app/components/taxonomy/taxonomy.js
> AC#1114/taxonomy table ordering

- src/app/components/cells/link/LinkOverlaySearchBar.jsx
- src/locales/de/profile.json
> AC1117: Keep focus in link filter input

- src/app/components/cells/link/LinkOverlaySearchBar.jsx
> Allow releasing focus in filter input

- src/app/components/Router.jsx
- src/app/components/tableView/applyFiltersAndVisibility.jsx
- src/app/redux/actionCreators.jsx
War deutlich aufwändiger als erwartet, die Änderungen an der exakt richtigen Stelle zu machen um Race-Conditions zu vermeiden.
> AC#1111: Allow deep links to archived data

- src/app/components/header/filter/FilterPopup.jsx
> AC#1120: Apply search when `Enter` is pressed

- src/app/components/tableView/applyFiltersAndVisibility.jsx
> AC#1130: [Regression] Hide group member columns

- src/app/components/header/tableSwitcher/TableSwitcherPopup.jsx
> fix: initial group filter

- src/app/components/overlay/ConfirmDependentOverlay.jsx
- src/app/components/table/VirtualTable.jsx
> Small bugfixes

- src/app/components/header/ResetTableViewButton.jsx
- src/app/components/profile/ProfileSettings.jsx
- src/app/components/tableView/TableView.jsx
- src/app/helpers/localStorage.js
- src/app/redux/actionCreators.jsx
- src/app/redux/reducers/globalSettings.js
- src/app/redux/reducers/tableView.js
- src/locales/de/profile.json
- src/locales/en/profile.json
- src/scss/profile.scss
- Tabellenspezifische-Persistierung von Zellenhervorhebung analog zu Filtern/Sortierung und Spaltensichtbarkeit
- Globale Einstellung "Zellenhervorhebung automatisch zurücksetzen" (default: false)
- Reset über "Tabellenansicht zurücksetzen" möglich
> AC#1146/persist annotations

- src/app/components/cells/identifier/IdentifierCell.jsx
- src/app/constants/TableauxConstants.js
- src/scss/cells/cell.scss
- src/scss/variables.scss
> AC#1168/update group column styling

- src/app/components/header/ColumnFilterPopup.jsx
- src/app/components/table/VirtualTable.jsx
- src/app/components/tableView/applyFiltersAndVisibility.jsx
> AC#1136: Bugfix for column behaviour

- src/app/components/contextMenu/RowContextMenu.jsx
- src/app/components/entityView/ItemPopupMenu.jsx
> GRUD_DEV-1122/only display cell annotation menu if user has edit permission

- src/app/components/table/VirtualTable.jsx
> GRUD_DEV-1125/use correct scrollInfo

- src/app/components/contextMenu/RowContextMenu.jsx
- src/app/components/entityView/ItemPopupMenu.jsx
- src/app/helpers/history.ts
> GRUD_DEV-1119: Open history from entity view

- src/app/components/table/tableNavigationWorker.jsx
> GRUD_DEV-1126/Fix visibleColumnOrdering in keyboard navigation

- src/app/components/table/tableNavigationWorker.jsx
> GRUD_DEV-1128/fix table copy and paste

- src/app/components/tableView/TableView.jsx
> refactor: move new row button

- src/app/components/header/ColumnFilterPopup.jsx
> GRUD_DEV-1141/keep rowId when jumping to column

- src/app/components/Router.jsx
- src/app/components/media/folder/File.tsx
- src/app/components/media/overlay/FileDependents.tsx
- src/app/helpers/apiRoutes.ts
- src/app/types/grud.ts
- src/locales/de/media.json
- src/locales/en/media.json
- src/scss/media.scss
- Overlay für Verknüpfungen im Media Management
> GRUD_DEV-1101/add file dependents overlay

- src/app/redux/actions/cellActions.test.js
> Adapt test to new `empty` value for currency cells

- .github/workflows/docker-image-ci.yml
> GRUD_DEV-1144/pr-checks

- src/app/components/cells/Cell.jsx
- src/app/components/cells/attachment/AttachmentCell.jsx
- src/app/components/cells/link/getVisibleLinkCount.js
- src/scss/cells/cell.scss
- src/scss/cells/link.scss
> GRUD_DEV-1140/fix multiple links in cell

- src/app/helpers/getDisplayValue.js
- src/app/helpers/getDisplayValue.test.js
> GRUD_DEV-1151/Fehler bei concatFormatPattern

- src/app/components/media/folder/File.tsx
- src/app/components/media/folder/Folder.tsx
- src/app/components/media/folder/Subfolder.tsx
- src/app/components/media/overlay/DirentMove.tsx
- src/app/helpers/apiRoutes.ts
- src/app/types/grud.ts
- src/scss/media.scss
> Grud_DEV-1150/dirent move parent folder link

- src/app/components/history/diffItems/CountryDiff.jsx
- src/scss/history/history.scss
> GRUD_DEV-1130/align currency diff
