- gulpfile.js
Usage: Add `--production` to the command line to set the node env to production. For example: `npm start --production`
> Look for production flag and exit process if error happens

- src/main/js/components/table/VirtualTable.jsx
This is caused by a bug in ampersand-collection, reported in 2015 and still unfixed: https://github.com/AmpersandJS/ampersand-collection/issues/54
> Fix LinkOverlay crashing on certain tables with constrained links

- src/main/js/dispatcher/GlobalCellChangeListener.js
- src/main/js/models/helpers/changeCell.js
A quick, hacky and hard-to-believe solution for ampersand-events not triggering the cell events in some cases.
Investigation is needed to find the cause of the problems.
> Workaround redraw problems

- src/main/js/components/table/tableNavigationWorker.js
- TableView won't catch system-copy shortcut (ctrl+c / cmd+c) when text is selected
- system-paste (ctrl+v / cmd+v) is only caught when not in editing mode
> Allow to copy selected text from table view to clipboard

- .npmrc
- package-lock.json
optional dependencies should be listed in package-lock.json on every platform. upgrade to npm >=5.6.0.
> fix package-lock.json and add npmrc

- src/app/components/history/HistoryBody.jsx
- src/app/components/history/differ.js
- src/app/components/history/history-helpers.js
We also add current files' display values to the shared
link/attachment diff visualiser. We don't check if files have been
deleted since, because to do so we would need to fetch all files and
check for 404 responses, also we can not retrieve name changes this
way. This should not matter too much, as a file is either there, or it
isn't.
> Fix attachment history always showing "item was deleted"

- src/app/components/markdownEditor/EditorPanel.jsx
- src/app/components/markdownEditor/LinkEditor.jsx
- src/app/components/markdownEditor/StyleControls.jsx
- src/scss/markdownEditor.scss
This adds buttons for `strikethrough` and a miniature UI to add and remove links to selected text.
Please note that the link UI lacks styling, and only review the technical aspects.
> Support more editing styles

- src/app/components/entityView/ItemPopupMenu.jsx
function call had wrong parameters
> fix showDependency in ItemPopupMenu of EntityView

- src/app/components/markdownEditor/LinkEditor.jsx
- src/app/components/markdownEditor/StyleControls.jsx
- src/scss/markdownEditor.scss
When focussing the URL-input field, we lose the visual indicator which element will be transformed to a link from the edit area. As a workaround we set the `underline` style to the currently selected fraction of text when entering the link editor, and use CSS to transform it to visually highlight the selection (and we remove the style when leaving the editor).
We can safely exploit the `underline` style this way as it has no counterpart in standard markdown, so it will get stripped by the markdown processor, should we accidently save while any text is highlighted this way.
Note that no style guidance exists yet for the visual editor anyway, so please do not review the visuals for anything but their existence.
> Visualise edited link elements

- src/app/components/header/NavigationPopup.jsx
- src/app/helpers/apiHelper.js
- src/app/helpers/authenticate.jsx
- src/app/helpers/userNameHelper.js
- Share one common function to disable auth for local development (based on feature flag)
- modify `getLogin()` so we don't try to call non-existing auth endpoints when auth is disabled
> Refactor dev mode

- .gitignore
- dev-server.js
- src/app/components/dashboard/support/SupportWidget.jsx
- src/app/constants/TableauxConstants.js
- src/app/helpers/authenticate.jsx
- src/index.js
- src/static/ServerConfigTool.js
- src/static/grud-frontend-server.js
As our webapp gets compiled before delivery, we can not pass environment parameters to it when we serve it. To solve this problem, we add an endpoint to the dev- and productions servers which deliver the server's runtime config, and then `fetch` that config into the app's memory at GRUD start.
> Use auth params in production artefact

- src/app/components/Router.jsx
- src/app/components/tableView/TableView.jsx
- src/locales/de/table.json
- src/locales/en/table.json
- src/scss/layout.scss
If there exists no table an user is allowed to see, we display an
empty table view without table-modifying controls instead of crashing
the GRUD.
> Add fallback for empty tables list

- README.md
- src/app/FeatureFlags.js
- src/app/helpers/authenticate.jsx
- src/app/helpers/connectionWatcher.js
- src/app/initGrud.js
- await authentication before pinging server status (else strange things may happen)
- add env var `AUTH_REQUIRED=[true,false]` for `dev` and `build` tasks (ignored at `start` task!)
- warn for missing auth config params when auth is enabled
> Allow disabling auth via env params

- src/app/components/overlay/EntityView/EntityViewBody.jsx
Instead of doing complex lookups and synching, we make sure the popup always gets passed the current cell instead of the stale copy that was used to open it.
> Fix translation view not reflecting EV changes

- src/app/helpers/RowConcatHelper.js
If the only id column of a table is of array type, like links or
attachments, trying to retrieve a proper translation would crash the
GRUD as arrays don't match the data type expected by the translation
helper.
> Prevent row concat helper crashing on array columns

- src/app/components/cells/text/TextCell.jsx
- src/app/components/header/ColumnFilterPopup.jsx
- src/app/components/header/tableSettings/NameEditor.jsx
- src/app/components/header/tableSwitcher/TableSwitcher.jsx
- src/app/components/header/tableSwitcher/TableSwitcherPopup.jsx
- src/app/components/overlay/EntityView/columnFilter.js
One of them caused overlay contexts to crash in some occasions,
e. g. on text edit overlays of newly duplicated rows.
> Replace some leftover manual translations with helper

- src/app/components/entityView/numeric/NumericView.jsx
- src/app/components/helperComponents/NumberInput.jsx
In fact it's even better, as it toggles sign every time user hits
`minus`, no matter where the caret is.
> Allow typing negative numbers

- src/app/components/helperComponents/NumberInput.jsx
When selecting an empty numeric cell, deleting the auto-generated zero, and then typing a minus sign as first character, the number input would automatically normalise this non-numeric input to an empty input.
This patch allows a numeric field with only a minus sign in it while typing, while still avoiding multiple minus signs and delivering a normal numeric value to its outside callbacks.
> Allow typing just minus sign in numbers

- src/app/components/helperComponents/connectOverlayToCellHOC.jsx
RowView in  EntityView didn't get updates of columnDescription, so we connect the column to the store.
> add column to cell HOC

- src/app/redux/actionCreators.js
We didn't check if the visible Columns from local storage exist or are
empty, so sometimes we set visibleColumns to undefined
> Fix initial visible Columns

- README.md
- src/app/FeatureFlags.js
- src/app/components/contextMenu/RowContextMenu.jsx
- src/app/components/header/tableSettings/TableSettings.jsx
- src/scss/filter.scss
- src/scss/tableSettings.scss
This adds `ENABLE_HISTORY` and `SHOW_TABLE_DROPDOWN` feature flag. For deployment, they need to be present as environment values at buildtime. Both default to `true`.
Disable respective features by setting them to `false`. Check is string comparison to `"false"`.
This is just a q&d implementation, as a much more sophisticated solution exists in the `feature/auth` branch.
> [Deployment] Add some buildtime feature flags

- src/app/components/header/tableSwitcher/TableSwitcher.jsx
- src/app/components/header/tableSwitcher/TableSwitcherPopup.jsx
Rename prop so it will be found and used by the `react-onclickoutside`
decorator, too.
> Fix table switcher popup error

- .dockerignore
- .gitignore
- .npmrc
- Dockerfile
- Jenkinsfile
- package.json
Hängende builds nicht gelöst, aber mehr verboses logging eingebaut und timeout.
Außerdem wird nun die BUILD_ID per arg in den docker build übergeben, dann muss nicht der ganze .git Ordner mit kopiert werden.
> Build hang

- src/app/redux/reducers/tableView.js
Forgot to clean up the columnOrdering on table switch,
leading missing columns or fatal crashes in getCell.
> Fix crash on Table-switch

- src/app/components/overlay/Overlays.jsx
Because of an error in the Overlays-component, exitingOverlays didn't
have the right structure, leading to the removal animation never
playing.
> Fix delay when an Overlay gets removed.

- src/app/components/cells/currency/currencyHelper.js
- src/app/components/history/differ.js
- src/scss/history/history.scss
Hier gab es ein Problem mit unveränderten Werten -- für die konnte kein Wert nachgeschlagen werden, weil der Diff `null` war.
Allerdings wird die letzte Änderung immer geklont, damit wir mit dem unveränderten Wert/leeren Diff die `aktueller Wert` Zeile füllen können. Bei den anderen Zelltypen klappt das, Currency ist aber ein Spezialfall beim Darstellen der Werte.
> Stop currency history from crashing GRUD

- dev-server.js
- src/app/FeatureFlags.js
- src/app/components/contextMenu/RowContextMenu.jsx
- src/app/components/header/tableSettings/TableSettings.jsx
- src/app/helpers/authenticate.jsx
- src/static/ServerConfigTool.js
- src/static/grud-frontend-server.js
Das erlaubt uns, Feature flags auch im Production mode beim Start des Servers zu setzen, somit muss man keinen dedizierten Rebuild mehr triggern um ein Featureflag zu setzen.
> Read feature flags from env

- src/app/components/table/GrudGrid.jsx
Only translate non-hovered grid, else the hovered grid scrolls double as fast.
> fix scroll lag

- src/app/components/cells/currency/CurrencyCell.jsx
Move onClickOutside from CurrencyEditCell to CurrencyCell
- [x ] This is not a duplicate of another PR
- [x ] The correct target branch selected?
- [ x] No existing features have been broken (without good reason)
- [x ] Commit messages are meaningful
- [x ] The behaviour is as the documentation describes, or you updated the docs
- Tests
- [x ] Tests have been added/updated for new/modified unit-testable functions/helpers
- [x ] Test were run and did pass
- [x ] The linter was run and did pass
When clicking the scrollbar in a currency-cell, the cell closed.
Fixed by moving onClickOutside handler from CurrencyEditCell to CurrencyCell.
> Fix CurrencyCell closing when clicking the scrollbar

- src/app/components/history/diffItems/Diff.jsx
- src/app/components/history/diffItems/NumberDiff.jsx
- [x ] This is not a duplicate of another PR
- [x ] The correct target branch selected?
- [ x] No existing features have been broken (without good reason)
- [ x] Commit messages are meaningful
- [x ] The behaviour is as the documentation describes, or you updated the docs
- Tests
- [ x] Tests have been added/updated for new/modified unit-testable functions/helpers
- [x ] Test were run and did pass
- [x ] The linter was run and did pass
NumberDiff Items in history always showed formatted number values with separator, now check for separator flag and format number only when needed.
Task: https://app.activecollab.com/116706/projects/2?modal=Task-21691-2
> add separator check to NumberDiff item

- src/app/components/columns/ColumnHeader.jsx
If a user is not allowed to see hidden tables, the find operation will
return null, leading to errors down the line. Remove it, as it isn't
necessary.
- Tests
Fixes null error when trying to open ColumnEditor if user doesn't have permission to see hidden tables.
Task: https://app.activecollab.com/116706/projects/2?modal=Task-21698-2
> Remove unnecessary table find

- src/app/components/table/tableNavigationWorker.js
- Tests
The copy and paste handlers in tableNavigationWorkers extracted the colum index from visible columns, leading to wrong indices in certain cases, fixed by using the whole columns array.
> fix wrong column Index on keyboard cell copy

- Dockerfile
Fix broken ci build due to missing jest setup file (setupTests.js) for ci tests.
`setupTests.js` was introduced in project-maintenance PR #272.
> fixed missing jest setup file for ci tests

- src/app/components/helperComponents/LinkList.jsx
- src/scss/overlay.scss
Fixes LinkView and AttachmentView in EntityView not being scrollable.
> Fix LinkList not scrollable

- src/app/components/frontendService/ContextMenuEntries.jsx
- src/app/components/frontendService/MainMenuEntry.jsx
- src/app/components/frontendService/ServiceLink.jsx
- src/app/frontendServiceRegistry/ServiceIcon.jsx
- src/app/frontendServiceRegistry/frontendServiceHelper.js
Our service item specification lists an optional `config.target`-property which should cause service entries to open in new tabs if set to `_blank`.
This PR also adds the generic `ServiceIcon` component to the context menu entries. Take care when using large images/SVGs as icons!
Remaining differences to the frontend service spec:
- not all service types are supported yet (most lack specification details)
- only the following scopes are used: `global`, `cell`
> Allow opening frontend services in new tabs

- src/app/components/markdownEditor/PlainMarkdownEditor.jsx
Disable mode switching buttons and always shows the rich text editor in horizontal split mode, as CodeMirror does not use correct mouse pointer/caret positions when selecting text.
> AC-971: Temporary display switching markdown modes

- src/app/components/overlay/EntityView/HeaderPopupMenu.jsx
Hier passiert es live in einer Tabelle, dass das Overlay crasht, weil `rows[tableId]` `undefined` ist und deswegen nicht auf `.data` zugegriffen werden kann.  
Vermutlich liegt das an einem Timing-Problem, und es wird ein Re-Render getriggert, während die entsprechende Tabelle gerade noch geladen wird. Da die so gefundene Zeile erst nach dem Öffnen des Popup-Menüs überhaupt gebraucht werden wurden die Aufrufe so abgeändert, dass sie gegen `nil` toleranter sind.
> Harden HeaderPopupMenu

- src/app/components/cells/text/ShortTextCell.jsx
- src/app/components/header/ColumnFilter.jsx
- src/app/components/tableView/applyFiltersAndVisibility.js
Blended `hidden` Spalten in der Tabellenansicht sowie im Spaltenfilter aus.  
1. Versteckte Werte werden bei allen Berechnungen (Filter "irgendeine Spalte enthält", Status, Werte von Group-Columns, ...) weiter berücksichtigt.  
2. Die Sichtbarkeit wird zweimal redundant auf leicht verschiedene Arten berechnet; das erspart uns aber, bei allen möglichen Operationen auf dem Redux-State entscheiden zu müssen ob wir die Sichtbarkeit mit einrechnen müssen oder nicht (wird sie immer, siehe 1.).
Die Lösung ist vom Code her sicher nicht die schönstmögliche, allerdings äußerst pragmatisch und effektiv.
> Hide `hidden` columns

- src/app/components/history/RevisionItem.jsx
- src/app/components/history/diffItems/LinkDiff.jsx
- src/app/components/history/history-helpers.js
- src/app/helpers/functools.js
Das problem sind nicht Multilangwerte bei Links, sondern dass Linkspalten als multilang definiert sind. Links und Attachment sind IMMER single lang, egal was in der Column steht.  
Hier wurde sich auf den `languageType`-Wert der Spalte verlassen und daher ist das Filtern gebrochen.  
Um das Problem überhaupt zu finden habe ich erst mal eine der Kernfunktionen refakturiert. Da das Ergebnis dann insgesamt performanter ist und auch bei langen Änderungshistorien nicht mehr abstürzen kann habe ich es dann so gelassen, auch wenn es etwas mehr Änderung als nötig ist.
> AC-1022: Fix multilang link/attachment history entries

- src/app/components/table/VirtualTable.jsx
- src/app/helpers/functools.js
Das scheint ein [Problem innerhalb von `react-virtualized`](https://github.com/bvaughn/react-virtualized/issues/830) zu sein. Dort wird der Index mit einem "normalen" Nummerncheck überprüft, aber logischerweise ist ja Not-A-Number in JS eine Zahl. Dieses NaN kann in der GRUD statt dem JS-konventionellen -1 auftauchen, wenn der Index einer Spalte nicht gefunden wird.
> [bugfix] AC-1025 - Changing visible columns can crash the frontend

- src/app/components/cells/Cell.jsx
-> [#1005: Farbliches hervorheben von Read-Only Spalten](https://app.activecollab.com/116706/projects/2/tasks/46240)
> [Bugfix] AC-1005: use disabled column styling on missing edit cell value permission

- .eslintrc
- src/app/components/header/filter/FilterPopup.jsx
- src/app/components/header/filter/FilterPopupFooter.jsx
- src/app/components/table/RowFilters.js
- src/app/components/tableView/applyFiltersAndVisibility.jsx
- src/app/helpers/DisplayValueWorkerControls.js
- src/app/helpers/buildClassName.js
- src/app/redux/redux-helpers.js
[AC#1049](https://app.activecollab.com/116706/projects/2?modal=Task-51032-2) - Wenn eine Tabelle mit Deep-Link geöffnet wird und gleichzeitig ein Filter für die Zieltabelle im LocalStorage persistiert ist stellen wir sicher, dass die Zeile des Deep-Links immer sichtbar ist.
Das Verhalten ist jetzt:
- Wenn ein Filter gesetzt ist und eine Zeile per Deep-Link vorausgewählt wird, dann hat der Deep-Link Vorrang, die Zeile ist sichtbar.
- Wenn die Tabelle bereits geladen wurde und wir den Filter per Popup ändern hat die Filterfunktion Vorrang, die ausgewählte Zeile verschwindet, wenn sie nicht Teil des Suchergebnisses ist.
Das hat ein paar Implikationen:
- Wenn die gewählte Zeile nicht Teil des Suchergebnisses ist wird sie vor allen Suchergebnissen angezeigt, um Probleme mit der Sortierung zu …
> Keep deep-linked row visible

- src/app/components/cells/Cell.jsx
- src/app/components/table/VirtualTable.jsx
Beim Klick auf eine leere Linkzelle wird der Fokus im Anschluss auf
`document.body` gesetzt.  
Der Grund hierfür ist erst mal nicht ersichtlich, da die Klick-Events in der
`Cell`-Komponente behandelt werden , nicht in den verschiedenen Zelltypen;
ebenso ist die Klickfläche auch bei leeren Linkzellen korrekt.  
Ein Hotfix ist jetzt erst mal Symptombekämpfung indem nach dem Klick der Fokus
wieder auf die angeklickte Zelle gesetzt wird, sollte er verlorengegangen sein.
> Keep focus when clicking link cells

- src/app/components/cells/Cell.jsx
- src/app/components/cells/boolean/BooleanCell.jsx
- src/app/components/cells/currency/CurrencyCell.jsx
- src/app/components/cells/currency/CurrencyEditCell.jsx
- src/app/components/cells/date/DateEditCell.jsx
- src/app/components/cells/link/LinkEditCell.jsx
- src/app/components/cells/link/LinkOverlay.jsx
- src/app/components/cells/text/ExpandButton.jsx
- src/app/components/cells/text/TextCell.jsx
- src/app/components/cells/text/TextEditOverlay.jsx
- src/app/components/contextMenu/RowContextMenu.jsx
- src/app/components/table/VirtualTable.jsx
- src/app/helpers/accessManagementHelper.js
- Text-, Richtext- und Boolean-Zellen haben bei Linksklick sofort zum
Editiermodus gewechselt.
- Fokussierte Text-, Richtext-, Link- und Attachment-Zellen haben bei
Rechtsklick zum Editiermodus gewechselt, anstatt das Kontextmenü anzuzeigen.
- Zell-Klickhandler für Links- und Rechtsklick waren stark vermischt ->
Refaktor, Funktionalitäten getrennt
- Durch die vermischten Funktionalitäten mussten wir anfangen, höhere Priorität
zu simulieren indem wir statt auf `click` schon auf `mousedown` gehört haben,
das konnte wieder zurückgesetzt werden
> [Bugfix]: Fix cell click handler regressions

- src/app/components/cells/Cell.jsx
Das verbietet allerdings generell, in den Zellen Shift-Multiselect zu machen.  
Eine Alternative wäre es, den ausgewählten Range dann zu löschen, wenn es sich um einen reinen Zell-Multiselekt handelt, das hätte allerdings den Nachteil, dass die Textselektion kurz hässlich aufflackern würde.
Meinungen dazu?
> AC#1061: Prevent text selection on shift-click

- src/app/components/contextMenu/RowContextMenu.jsx
- src/scss/contextMenu.scss
Der Auto-Linter hat im SCSS zugeschlagen und u.A. mindetens ein fehlendes Semikolon nachgetragen. Mit "hide whitespace" sind die Changes minimal.
> Move and separate destructive row context menu actions

- Dockerfile
- Jenkinsfile
- setupTests.js
- src/app/archivedRows/ToggleArchivedRowsButton.jsx
- src/app/archivedRows/helpers.js
- src/app/components/cells/Cell.jsx
- src/app/components/cells/link/LinkOverlay.jsx
- src/app/components/cells/link/LinkOverlayCache.jsx
- src/app/components/cells/text/TextEditOverlay.jsx
- src/app/components/contextMenu/RowContextMenu.jsx
- src/app/components/history/diffItems/FlagDiff.jsx
- src/app/components/overlay/EntityView/EntityViewBody.jsx
- src/app/components/table/RowFilters.js
- src/app/components/tableView/TableView.jsx
- src/app/helpers/annotationHelper.js
- src/app/helpers/apiHelper.js
- src/app/redux/actionCreators.jsx
- src/app/redux/actions/cellActions.js
- src/app/redux/actions/rowActions.js
- src/app/redux/reducers/rows.js
- src/locales/de/table.json
- src/locales/en/table.json
- src/scss/cells/cell.scss
- src/scss/cells/metaCell.scss
- src/scss/filter.scss
Braucht das latest greatest Backend.
> [Archive]: Connect to backend

- src/app/RowFilters/AnyColumn.js
- src/app/RowFilters/Number.js
- src/app/RowFilters/index.js
- src/app/components/header/filter/FilterPopup.jsx
- src/app/components/header/filter/helpers.js
- src/app/constants/TableauxConstants.js
- src/locales/de/table.json
- src/locales/en/table.json
- tests/rowFilters/rowFilters.ng.test.js
> AC#1121: Any column contains filter

- src/app/components/header/filter/FilterPopup.jsx
- src/app/components/header/filter/FilterRow.jsx
- src/app/components/header/filter/helpers.js
Hier noch der fehlende Teil in der Frontendsuche, der in den Filterbäumen beim Einlesen eines Pipe-Zeichens im Value OR-verknüpfte Branches hinzufügt bzw. für die Anzeige die Einzelwerte dieser Branches wieder mit Pipe konkateniert.
Es ist keinerlei komplexere Logik impliziert, die prüfen würde ob ein "Oder" an dieser Stelle wirklich eine sinnvolle Suche erzeugt. Man kann beispielsweise "Gewicht kleiner als '100|80'" eingeben. Suchinputs werden einfach geparst und in dem Fall zwei Suchen erzeugt, die dann "Gewicht kleiner als 100" OR "Gewicht kleiner 80" auswerten.
> Add OR filtering by pipe `|`

- src/app/components/tableView/applyFiltersAndVisibility.jsx
- Einblendbare Grupppenspalten sind wieder einblendbar
- Normale Suche dominiert nicht mehr die Spaltensichtbarkeit
- Suche nach Annotations/"irgendeine Spalte enthält" fixiert Spalten mit Treffern als sichtbar, andere Spalten können weiterhin vom User ein-/ausgeblendet werden
**Edit:** Nein, es ist nicht ohne erheblichen weiteren Aufwand möglich, visuelles Feedback zu fixierten Spalten anzuzeigen.
> Fix some column visibility issues

- src/app/redux/reducers/tableView.js
Mit aktivierter User-Einstellung "Spaltenansicht automatisch zurücksetzen"
konnte es dazu kommen, dass die Sortierung und Sichtbarkeit der Spalten falsch initialisiert wurde.
Mit der Änderung im PR wird sichergestellt, dass für die initiale Sortierung und Sichtbarkeit die richtigen Spaltendaten verwendet werden.
> AC#1142/Fix Frontend Crash

- src/app/components/header/filter/FilterSavingPopup.jsx
- src/app/components/header/tableSettings/NameEditor.jsx
- src/app/components/header/tableSettings/TableSettings.jsx
- src/app/components/header/tableSettings/TableSettingsPopup.jsx
- src/app/components/markdownEditor/LinkEditor.jsx
- src/app/components/markdownEditor/StyleControls.jsx
Das useOutsideClick-Paket funktioniert nur mit Klassenkomponenten. Der alte Babel/Parcel-Workflow hat alle Komponenten intern zu Klassenkomponenten transformiert, weswegen das vorher funktioniert hatte, obwohl formal falsch.
> AC#1163: Fix crash on opening "save filter" dialog

- src/app/components/cells/identifier/IdentifierCell.jsx
- src/app/helpers/getDisplayValue.js
Beinhaltet die Frontendanpassungen zu [#1152: Formatpatterns bei concat-columns/links](https://app.activecollab.com/116706/projects/2/tasks/61988)
Kann zusammen mit dem [Backend-PR](https://github.com/campudus/tableaux/pull/296) getestet werden:
- Tabelle updaten mit einem `concatFormatPattern`, welches alle identifier-Spalten beinhaltet (bspw. `"{{1}} | {{2}}"`)
> AC#1152/add formatPattern for concat column

- src/app/components/helperComponents/NumberInput.jsx
- src/app/components/history/diffItems/NumberDiff.jsx
- Führt eine Ober- und Untergrenze für Integer-Inputs ein, so dass Werte ohne
Exception im Backend gespeichert werden können
- Stellt sicher, dass in der History von Numeric-Werten immer alle
Nachkommastellen angezeigt werden
> Bugfixes for numeric cells

- package-lock.json
In einem der letzten PRs sind aus der package-lock für die tools die native binaries nutzen (esbuild, rollup, sass-embedded) die optionalen dependencies für die unterschiedlichen Plattformen (arm, x64 etc.) rausgeflogen.
Es ist wichtig, dass in der package-lock die optionalen dependencies für alle Plattformen enthalten sind, da erst zur Installation die jeweilige binary für die genutzte Plattform installiert wird.
Aktuell ist in der package-lock nur die binary für `linux-x64` enthalten, d.h. bei allen anderen Plattformen (bspw. bei mir auf dem Mac mit `darwin-arm64`) kommt es beim Start der App zu einem Fehler, da während der Installation die falsche binary installiert wurde.
> fix/add back native multi-plattform optional dependencies

- src/app/components/entityView/numeric/NumericView.jsx
Hm. Suspicious, dass das vorher anders funktioniert haben soll…
> GRUD_DEV-1064: Exclude C-c and C-v from blocked keys in numerics

- package-lock.json
- package.json
Durch das Update von Vite auf v6.3.4 gab es eine Regression dass cross-module cyclic imports auf einen Fehler laufen. ([Vitest with Vite 6.3.x regressed and started failing](https://github.com/vitest-dev/vitest/issues/7902))
Diese Regression wurde in v6.3.5 gefixt ([Changelog](https://github.com/vitejs/vite/blob/main/packages/vite/CHANGELOG.md#635-2025-05-05)).
> fix: update vite to 6.3.5

- Dockerfile
- src/app/helpers/multiLanguage.test.js
Die ENV-Konfiguration für Internationalization unterscheidet sich zwischen Docker-Container und lokal.
Dadurch kommt es bei der Nutzung der [Intl-API](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Intl) zu unterschiedlichen Ergebnissen.
Grundsätzliches Problem ist eine Fehlannahme bzgl. locale-Resolution bei einigen Tests:
`new Intl.NumberFormat("US")` verwendet nicht wie angenommen immer das locale `en-US` zum formatieren, sondern das im System eingestellte default-locale.
Das locale kann nicht anhand der country resolved werden! ("US" oder "GB" -> default-locale; "DE" wird nur richtig resolved, weil es sich nur im Casing von "de" unterscheidet).
Das lässt sich einfach prüfen über:
```sh
docker run --rm node:22.14-alpine node -p 'new …
```
> GRUD_DEV-1143/fix intl errors

- Dockerfile
`NODE_ENV=production` unterbindet die Installation von devDependencies bei `npm i` und `npm ci`. 
Dadurch läuft der Docker Build gerade auf Fehler, weil de nötigen Dependencies für Linting und Testing nicht gefunden werden.
> GRUD_DEV-1143/remove NODE_ENV from Dockerfile

- src/app/redux/reducers/selectedCell.js
Kleiner Bugfix als Nachtrag zu den Änderungen zu GRUD_DEV-1146:
Fixed wiederholtes öffnen des Overlay in Spalten vom Typ "text"
> GRUD_DEV-1146/fix-toggle-cell-editing

- src/app/components/table/VirtualTable.jsx
Dies scheint der minimalste Eingriff sein, der verhindert, dass aggressives
Fokussetzen das Bedienen von Popups (Fokusswitcher, Filterpopup) verhindert,
nachdem eine Zeile gelöscht wurde. Es kann dazu führen, dass in bestimmten
Edge-Cases (z.B. nach Bedienung von Overlays) jetzt nochmal auf die Tabelle
geklickt werden muss, bevor man die Tastaturnavigation wieder benutzen kann.
Usertesting ausdrücklich erwünscht!
> GRUD_DEV-1148: Fokusprobleme

- src/app/helpers/DisplayValueWorkerControls.js
- src/app/redux/reducers/tableView.js
Nach dem Löschen eines Datensatzes läuft Redux in einen Infinite-Loop beim Generieren von DisplayValues.
Als Kriterium, ob DisplayValues generiert werden sollen dient u.A. ein Vergleich zwischen der Anzahl der Rows und der Anzahl der DisplayValues. Ist die Anzahl ungleich wird ein Update der DisplayValues angestoßen.
Nach dem Löschen einer Row ist die Anzahl nicht mehr gleich.
Beim Generieren der DisplayValues fließt aber die bereits gelöschte Row noch mit ein (alter state?, race-condition?).
D.h. nach dem Update der DisplayValues ist die Anzahl immernoch ungleich -> Infinite Loop.
Im PR wurde der Vergleich zwischen der Anzahl der Rows und der Anzahl der DisplayValues so angepasst, dass ein Update der DisplayValues nur angestoßen wird, wenn weniger DisplayValues vorhanden sind als Rows. …
> GRUD_DEV-1175/fix infinite loop after delete
